App.Product = DS.Model.extend(
  name: DS.attr('string')
  description: DS.attr('string')
  price: DS.attr('string')
  available_on: DS.attr('string')
  permalink: DS.attr('string')
  meta_escription: DS.attr('string')
  meta_keywords: DS.attr('string')
  taxon_ids: DS.attr('string')
  product_properties: DS.hasMany('App.ProductProperty')
  variants: DS.hasMany("App.Variant")
)